# fly.toml app configuration file generated for tatiatic-user-api on 2023-08-07T10:50:29+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tatiatic-user-api"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[build.args]
  STG="prd"
  DB_UR="***"
  DB_NA="***"
  DB_ID="***"
  DB_PA="***"

[http_service]
  internal_port = 9876
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 3
  processes = ["app"]
